In [1]:
%load_ext autoreload
%autoreload 2

In [11]:
import pandas as pd
import tensorflow as tf

from dice_rl_plugins.applications.medical_rl.continuous.config import *
from dice_rl_plugins.utils import print_namedtuple

pd.set_option("display.max_rows", 100)
pd.set_option("display.max_column", None)

In [30]:
n = 20
m = 4

display( test.head(n+1) )

print_namedtuple(
    tf.nest.map_structure(
        lambda t: t[:n+10*m, ...], dataset.get_all_steps(include_terminal_steps=True), )
)

ID  Length of Stay  ACTH max  ACTH mean  ACTH min  ACTH std  \
0   10342.0               0 -0.080002  -0.088658 -0.088606 -0.025408   
1   10342.0               1 -0.080002  -0.088658 -0.088606 -0.025408   
2   10342.0               2 -0.080002  -0.088658 -0.088606 -0.025408   
3   10342.0               3 -0.080002  -0.088658 -0.088606 -0.025408   
4   19383.0               0 -0.080002  -0.088658 -0.088606 -0.025408   
5   19383.0               1 -0.080002  -0.088658 -0.088606 -0.025408   
6    3458.0               0 -0.080002  -0.088658 -0.088606 -0.025408   
7    3458.0               1 -0.080002  -0.088658 -0.088606 -0.025408   
8    3458.0               2 -0.080002  -0.088658 -0.088606 -0.025408   
9    3458.0               3 -0.080002  -0.088658 -0.088606 -0.025408   
10   3458.0               4 -0.080002  -0.088658 -0.088606 -0.025408   
11   3458.0               5 -0.080002  -0.088658 -0.088606 -0.025408   
12   3458.0               6 -0.080002  -0.088658 -0.088606 -0.025408   
13   3458.0               7 -0.080002  -0.088658 -0.088606 -0.025408   
14   3458.0               8 -0.080002  -0.088658 -0.088606 -0.025408   
15   3458.0               9 -0.080002  -0.088658 -0.088606 -0.025408   
16   7047.0               0 -0.080002  -0.088658 -0.088606 -0.025408   
17   7047.0               1 -0.080002  -0.088658 -0.088606 -0.025408   
18   7047.0               2 -0.080002  -0.088658 -0.088606 -0.025408   
19   7047.0               3 -0.080002  -0.088658 -0.088606 -0.025408   
20   9254.0               0 -0.080002  -0.088658 -0.088606 -0.025408   

    AF Monitor max  AF Monitor mean  AF Monitor min  AF Monitor std    AG max  \
0         1.851076         4.185046        4.659051        0.418099 -0.227794   
1         1.851076         4.185046        4.659051        0.418099 -0.227794   
2         1.851076         4.185046        4.659051        0.418099 -0.227794   
3         1.851076         4.185046        4.659051        0.418099 -0.227794   
4         1.851076         4.185046        4.659051        0.418099 -0.227794   
5         1.851076         4.185046        4.659051        0.418099 -0.227794   
6         1.851076         4.185046        4.659051        0.418099 -0.227794   
7         1.851076         4.185046        4.659051        0.418099 -0.227794   
8         1.851076         4.185046        4.659051        0.418099 -0.227794   
9         1.851076         4.185046        4.659051        0.418099 -0.227794   
10        1.851076         4.185046        4.659051        0.418099 -0.227794   
11        1.851076         4.185046        4.659051        0.418099 -0.227794   
12        1.851076         4.185046        4.659051        0.418099 -0.227794   
13        1.851076         4.185046        4.659051        0.418099 -0.227794   
14        1.851076         4.185046        4.659051        0.418099 -0.227794   
15        1.851076         4.185046        4.659051        0.418099 -0.227794   
16        1.851076         4.185046        4.659051        0.418099 -0.227794   
17        1.851076         4.185046        4.659051        0.418099 -0.227794   
18        1.851076         4.185046        4.659051        0.418099 -0.227794   
19        1.851076         4.185046        4.659051        0.418099 -0.227794   
20        1.851076         4.185046        4.659051        0.418099 -0.227794   

     AG mean    AG min    AG std  Albumin max  Albumin mean  Albumin min  \
0  -0.262609 -0.276975 -0.271069     0.162689      0.197672     0.229732   
1  -0.262609 -0.276975 -0.271069     0.162689      0.197672     0.229732   
2  -0.262609 -0.276975 -0.271069     0.162689      0.197672     0.229732   
3  -0.262609 -0.276975 -0.271069     0.162689      0.197672     0.229732   
4  -0.262609 -0.276975 -0.271069     0.162689      0.197672     0.229732   
5  -0.262609 -0.276975 -0.271069     0.162689      0.197672     0.229732   
6  -0.262609 -0.276975 -0.271069     0.162689      0.197672     0.229732   
7  -0.262609 -0.276975 -0.271069 


step_type
tf.Tensor(
[0 1 1 1 1 1 1 1 1 1 1 1 1 2 0 1 1 1 1 1 1 1 1 1 1 2 0 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 2 0 1 1 1 1 1 1 1 1 1 1 1 1 2], shape=(60,), dtype=int32)

step_num
tf.Tensor(
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13  0  1  2  3  4  5  6  7  8  9
 10 11  0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19  0  1
  2  3  4  5  6  7  8  9 10 11 12 13], shape=(60,), dtype=int32)

observation
tf.Tensor(
[[-0.0800016  -0.08865834 -0.08860586 ...  1.          0.
   0.        ]
 [-0.0800016  -0.08865834 -0.08860586 ...  1.          0.
   0.        ]
 [-0.0800016  -0.08865834 -0.08860586 ...  1.          0.
   0.        ]
 ...
 [-0.0800016  -0.08865834 -0.08860586 ...  4.          0.
   0.        ]
 [-0.0800016  -0.08865834 -0.08860586 ...  4.          0.
   0.        ]
 [-0.0800016  -0.08865834 -0.08860586 ...  4.          0.
   0.        ]], shape=(60, 382), dtype=float32)

action
tf.Tensor(
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 

In [44]:
print_namedtuple(
    dataset.get_step(batch_size=8, num_steps=2)
)


step_type
tf.Tensor(
[[1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 2]
 [1 1]], shape=(8, 2), dtype=int32)

step_num
tf.Tensor(
[[20 21]
 [13 14]
 [ 9 10]
 [ 8  9]
 [10 11]
 [87 88]
 [81 82]
 [12 13]], shape=(8, 2), dtype=int32)

observation
tf.Tensor(
[[[-0.0800016  -0.08865834 -0.08860586 ...  2.          0.
    1.        ]
  [-0.0800016  -0.08865834 -0.08860586 ...  2.          0.
    0.        ]]

 [[-0.0800016  -0.08865834 -0.08860586 ...  1.          0.
    0.        ]
  [-0.0800016  -0.08865834 -0.08860586 ...  1.          0.
    0.        ]]

 [[-0.0800016  -0.08865834 -0.08860586 ...  2.          0.
    1.        ]
  [-0.0800016  -0.08865834 -0.08860586 ...  2.          0.
    1.        ]]

 ...

 [[-0.0800016  -0.08865834 -0.08860586 ...  4.          0.
    0.        ]
  [-0.0800016  -0.08865834 -0.08860586 ...  4.          0.
    0.        ]]

 [[-0.0800016  -0.08865834 -0.08860586 ...  4.          0.
    0.        ]
  [-0.0800016  -0.08865834 -0.08860586 ...  4.          0.